"""empty message

Revision ID: e03616210d3c
Revises: 266c6a898807
Create Date: 2020-03-02 12:55:07.500683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03616210d3c'
down_revision = '266c6a898807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('link', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'link')
    # ### end Alembic commands ###
